### ISSUE TITLE
kerberos auth error

### ISSUE THREAD

**Issue by enj5oy** [zblurx/dploot#10]
Kerberos auth not work
![random](https://github.com/zblurx/dploot/assets/143943083/e3993aef-cf8c-4794-91cf-5344588a8642)

Kerberos with impacket
![dplootissues3kerberosImpacket](https://github.com/zblurx/dploot/assets/143943083/d70f2387-a43a-42a3-a226-1a725299bbe7)

**Comment by zblurx** [comment]
Hey, when using kerberos auth with ccache file, you must use `-use-kcache` flag. The classic `-k` will just force kerberos authentication with password or nthash. Let me know if this helped

**Comment by enj5oy** [comment]
@zblurx with -use-kcache all work
