### ISSUE TITLE
Dploot does not scan targets not exposing C$

### ISSUE THREAD

**Issue by Dfte** [zblurx/dploot#26]
Hey bro,

As mentionned here https://github.com/login-securite/DonPAPI/issues/85

Dploot does not scan hosts that do not expose the C$ share. Althought it limits its possibilities, it is still interesting to loot targets only via remote registry since we can still access LSA (scheduled tasks, winlogons, service credentials) as well as the SAM database. On the other side, it can also happen that a target prevents access to remote registry. While this is unusual, it may happen.

For that reason I reworked the is_admin function to the following:

```python
    def is_admin(self) -> Tuple[bool, bool, bool]:
        
        is_admin_via_remote_registry = is_admin_via_connect_tree = False
        # Checks if user is admin via remote registry and service manager
        # Code from Netexec https://github.com/Pennyw0rth/NetExec/blob/main/nxc/protocols/smb.py
        rpctransport = SMBTransport(self.smb_session._remoteHost, 445, r"\svcctl", smb_connection=self.smb_session)
        dce = rpctransport.get_dce_rpc()
        
        try:
            dce.connect()
        except Exception as e:
            logging.debug(f"DCE_CONNECT ERROR: {e}")
            is_admin_via_remote_registry = False
        else:
            with contextlib.suppress(Exception):
                dce.bind(scmr.MSRPC_UUID_SCMR)
            try:
                scmrobj = scmr.hROpenSCManagerW(dce, f"{self.smb_session._remoteHost}\x00", "ServicesActive\x00", 0xF003F)
                scmr.hREnumServicesStatusW(dce, scmrobj["lpScHandle"])
                logging.debug(f"User is admin on {self.smb_session._remoteHost} (checked via Remote Registry)")
                is_admin_via_remote_registry = True
            except scmr.DCERPCException:
                logging.debug(f"DCE_RPC_ERROR: {e}")
                is_admin_via_remote_registry = False
            except Exception as e:
                logging.debug(f"Error checking if user is admin on {self.smb_session._remoteHost}: {e}")
                is_admin_via_remote_registry = False
        
        # Checks if admin via connectree()
        try:
            self.smb_session.connectTree("C$")
            logging.debug(f"User is admin on {self.smb_session._remoteHost} (checked via SMB connectr tree)")
            is_admin_via_connect_tree = True
        except Exception:
            is_admin_via_connect_tree = False
        # Returns three values:
        # - Admins via connect tree (means smb crawling is possible)
        # - Admin via remote registry (means we can dump SAM, LSA and so on)
        # - Admins overall value (bitwise via OR bitwise)
        return (is_admin_via_connect_tree | is_admin_via_remote_registry), is_admin_via_connect_tree, is_admin_via_remote_registry
```
 
It does check if:
* Remote registry is accessible as admin (connecting to service manager)
* C$ share is accessible via classic smb connect tree function

The function now returns three values:
* (is_admin_via_connect_tree | is_admin_via_remote_registry) a OR bitwise operation that says whether or not we are admin 
* is_admin_via_connect_tree (means we can crawl SMB shares)
* is_admin_via_remote_registry (means we can loot remote registries)

That way, all we need to do is patch all functions calling for is_admin so that they take into account only the first value while the other two can be used later.

Let me know what you think about it ;)!

**Comment by zblurx** [comment]
Hey mamen @Dfte
Following our discussion on this topic, dploot relies on the C$ share being exposed in order to download masterkeys and dpapi blob in nearly every dploot actions. Also, there is already something to check for remote registry -> `enable_remoteops()` 

Howerver I agree maybe `is_admin()` function name needs to be clearer, what do you think ?

**Comment by Dfte** [comment]
Oye!!

Since Dploot relies on masterkeys, yeah. There is no need to add anything else here. That's however something we could add to DonPapi depending of whether or not we want to loot registry keys that could contain secrets such as autologon, lsa, sam and so on.

**Comment by zblurx** [comment]
@Dfte I can add an `is_remoteops_available()` function in DPlootSmbConnection class

**Comment by zblurx** [comment]
Closing as we will implement the check in donpapi directly
