### ISSUE TITLE
Updating Chrome and Edge paths

### ISSUE THREAD

**Issue by mxrch** [zblurx/dploot#3]
I think dploot cannot fetch Chrome (and sometimes Edge) data on newer systems because of the new paths, maybe there are all the information you need in https://github.com/login-securite/DonPAPI/pull/40 ? :)

**Comment by zblurx** [comment]
Hey, new paths have already been added. Can you provide a debug trace of the tool running ?

**Comment by mxrch** [comment]
Hey, debug is sensible data :eyes: but the debug trace prints everything ("Found MasterKey", "Found MSEDGE AppData files for user X") except Chrome related data

**Comment by mxrch** [comment]
But DonPAPI finds the cookies well, I tested both to debug a little

**Comment by zblurx** [comment]
I'll dig on it

**Comment by zblurx** [comment]
After some digging, I've may have found the problem : a dirty break. Fixed in 0fd2b6b232426ff74f22cea10ed88de110c7b8db.
Closing now, but if there is still a problem, anyone can react on this issue
