### ISSUE TITLE
credentials error

### ISSUE THREAD

**Issue by enj5oy** [zblurx/dploot#9]
module credentials can not decrypt credential blob
![dploot_issues2](https://github.com/zblurx/dploot/assets/143943083/19dd0a49-d0b8-408a-918e-10b702f54e86)

With mimikatz all fine
![dploot_issues](https://github.com/zblurx/dploot/assets/143943083/90d6942f-898e-4b63-92e4-c9d34f09f16e)

**Comment by zblurx** [comment]
Thanks for the issue ! I commited a fix, feel free to reopen if it's not good

**Comment by enj5oy** [comment]
@zblurx now all works!
